[System::Flags]
public enum class AsyncGetDataFlag
{
    DoNotFlush = D3D10_ASYNC_GETDATA_DONOTFLUSH
};

[System::Flags]
public enum class BindFlag
{
	VertexBuffer = D3D10_BIND_VERTEX_BUFFER,
	IndexBuffer = D3D10_BIND_INDEX_BUFFER,
	ConstantBuffer = D3D10_BIND_CONSTANT_BUFFER,
	ShaderResource = D3D10_BIND_SHADER_RESOURCE, 
	StreamOutput = D3D10_BIND_STREAM_OUTPUT,
	RenderTarget = D3D10_BIND_RENDER_TARGET,
	DepthStencil = D3D10_BIND_DEPTH_STENCIL
};

public enum class Blend
{
	Zero = D3D10_BLEND_ZERO,
	One = D3D10_BLEND_ONE,
	SourceColor = D3D10_BLEND_SRC_COLOR,
	InvertSourceColor = D3D10_BLEND_INV_SRC_COLOR,
	SourceAlpha = D3D10_BLEND_SRC_ALPHA,
	InvertSourceAlpha = D3D10_BLEND_SRC_ALPHA,
	DestinationAlpha = D3D10_BLEND_DEST_ALPHA,
	InvertDestinationAlpha = D3D10_BLEND_INV_DEST_ALPHA,
	DestionationColor = D3D10_BLEND_DEST_COLOR,
	InvertDestionationColor = D3D10_BLEND_INV_DEST_COLOR,
	SourceAlphaSaturate = D3D10_BLEND_SRC_ALPHA_SAT,
	BlendFactor = D3D10_BLEND_BLEND_FACTOR,
	InvertBlendFactor = D3D10_BLEND_INV_BLEND_FACTOR,
	Source1Color = D3D10_BLEND_SRC1_COLOR,
	InvertSource1Color =D3D10_BLEND_INV_SRC1_COLOR,
	Source1Alpha = D3D10_BLEND_SRC1_ALPHA,
	InvertSource1Alpha=D3D10_BLEND_INV_SRC1_ALPHA
};

public enum class BlendOperation
{
	 Add = D3D10_BLEND_OP_ADD,
	 Subtract = D3D10_BLEND_OP_SUBTRACT,
	 ReverseSubtract = D3D10_BLEND_OP_REV_SUBTRACT,
	 Minimum = D3D10_BLEND_OP_MIN,
	 Maximum = D3D10_BLEND_OP_MAX
};

public enum class ConstantBufferType
{
	ConstantBuffer = D3D10_CT_CBUFFER,
	TextureBuffer = D3D10_CT_TBUFFER	
};

[System::Flags]
public enum class CPU_AccessFlag
{
	Write = D3D10_CPU_ACCESS_WRITE,
	Read = D3D10_CPU_ACCESS_READ
};

[System::Flags]
public enum class CreateDeviceFlag
{
	SingleThreaded = D3D10_CREATE_DEVICE_SINGLETHREADED,
	Debug = D3D10_CREATE_DEVICE_DEBUG,
	SwitchToRef = D3D10_CREATE_DEVICE_SWITCH_TO_REF,
	PreventInternalThreadingOptimizations = D3D10_CREATE_DEVICE_PREVENT_INTERNAL_THREADING_OPTIMIZATIONS,
	AllowNullFromMap = D3D10_CREATE_DEVICE_ALLOW_NULL_FROM_MAP,
	BGRA_Support = D3D10_CREATE_DEVICE_BGRA_SUPPORT,
	StrictValidation = D3D10_CREATE_DEVICE_STRICT_VALIDATION
};

[System::Flags]
public enum class ClearFlag
{
	Depth = D3D10_CLEAR_DEPTH,
	Stencil = D3D10_CLEAR_STENCIL
};

public enum class ColorWriteEnable
{
	Red = D3D10_COLOR_WRITE_ENABLE_RED,
	Green = D3D10_COLOR_WRITE_ENABLE_GREEN,
	Blue = D3D10_COLOR_WRITE_ENABLE_BLUE,
	Alpha = D3D10_COLOR_WRITE_ENABLE_ALPHA,
	All = D3D10_COLOR_WRITE_ENABLE_ALL
};

public enum class ComparisonFunction
{
	Never = D3D10_COMPARISON_NEVER,
	Less = D3D10_COMPARISON_LESS,
	Equal =D3D10_COMPARISON_EQUAL,
	LessEqual = D3D10_COMPARISON_LESS_EQUAL,
	Greater = D3D10_COMPARISON_GREATER,
	NotEqual = D3D10_COMPARISON_NOT_EQUAL,
	GreaterEqual = D3D10_COMPARISON_GREATER_EQUAL,
	Always = D3D10_COMPARISON_ALWAYS
};

public enum class CounterEnum
{
	GpuIdle = D3D10_COUNTER_GPU_IDLE,
	VertexProcessing = D3D10_COUNTER_VERTEX_PROCESSING,
	GeometryProcessing = D3D10_COUNTER_GEOMETRY_PROCESSING,
	PixelProcessing = D3D10_COUNTER_PIXEL_PROCESSING,
	OtherGpuProcessing = D3D10_COUNTER_OTHER_GPU_PROCESSING,
	HostAdapterBandwidthUtilization = D3D10_COUNTER_HOST_ADAPTER_BANDWIDTH_UTILIZATION,
	LocalVideoMemoryBandwidthUtilization = D3D10_COUNTER_LOCAL_VIDMEM_BANDWIDTH_UTILIZATION,
	VertexThroughputUtilization = D3D10_COUNTER_VERTEX_THROUGHPUT_UTILIZATION,
	TriangleSetupThroughputUtilization = D3D10_COUNTER_TRIANGLE_SETUP_THROUGHPUT_UTILIZATION,
	FillrateThroughputUtilization = D3D10_COUNTER_FILLRATE_THROUGHPUT_UTILIZATION,
	VertexShaderMemoryLimited = D3D10_COUNTER_VS_MEMORY_LIMITED,
	VertexShaderComputationLimited = D3D10_COUNTER_VS_COMPUTATION_LIMITED,
	GeomertyShaderMemoryLimited = D3D10_COUNTER_GS_MEMORY_LIMITED,
	GeometryShaderComputationLimited = D3D10_COUNTER_GS_COMPUTATION_LIMITED,
	PixelShaderMemoryLimited = D3D10_COUNTER_PS_MEMORY_LIMITED,
	PixelShaderComputationLimited = D3D10_COUNTER_PS_COMPUTATION_LIMITED,
	PostTransformCacheHitRate = D3D10_COUNTER_POST_TRANSFORM_CACHE_HIT_RATE,
	TextureCacheHitRate = D3D10_COUNTER_TEXTURE_CACHE_HIT_RATE,
	DeviceDependent0 = D3D10_COUNTER_DEVICE_DEPENDENT_0
};

public enum class CounterType
{
	Float32 = D3D10_COUNTER_TYPE_FLOAT32,
	UINT16 = D3D10_COUNTER_TYPE_UINT16,
	UINT32 = D3D10_COUNTER_TYPE_UINT32,
	UINT64 = D3D10_COUNTER_TYPE_UINT64
};

public enum class CullMode
{
	None = D3D10_CULL_NONE,
	Front = D3D10_CULL_FRONT,
	Back = D3D10_CULL_BACK
};

public enum class DepthWriteMask
{
	Zero = D3D10_DEPTH_WRITE_MASK_ZERO,
	All =D3D10_DEPTH_WRITE_MASK_ALL
};


public enum class DeviceStateType
{
	StreamOutputBuffer = D3D10_DST_SO_BUFFERS,
	OutputMergeRenderTargets = D3D10_DST_OM_RENDER_TARGETS,
	OutputMergeDepthStencilState = D3D10_DST_OM_DEPTH_STENCIL_STATE,
	OutputMergeBlendState = D3D10_DST_OM_BLEND_STATE,
	VertexShader = D3D10_DST_VS,
	VertexShaderSampler = D3D10_DST_VS_SAMPLERS,
	VertexShader_ShaderResource = D3D10_DST_VS_SHADER_RESOURCES,
	VertexShaderConstantBuffer = D3D10_DST_VS_CONSTANT_BUFFERS,
	GeometryShader = D3D10_DST_GS,
	GeometryShaderSampler = D3D10_DST_GS_SAMPLERS,
	GeometryShader_ShaderResource = D3D10_DST_GS_SHADER_RESOURCES,
	GeometryShaderConstantBuffer = D3D10_DST_GS_CONSTANT_BUFFERS,
	PixelShader = D3D10_DST_PS,
	PixelShaderSampler = D3D10_DST_PS_SAMPLERS,
	PixelShader_ShaderResource = D3D10_DST_PS_SHADER_RESOURCES,
	PixelShaderConstantBuffer = D3D10_DST_PS_CONSTANT_BUFFERS,
	InputAssemblerVertexBuffer = D3D10_DST_IA_VERTEX_BUFFERS,
	InputAssemblerIndexBuffer = D3D10_DST_IA_INDEX_BUFFER,
	InputAssemblerInputLayout = D3D10_DST_IA_INPUT_LAYOUT,
	InputAssemblerPrimitiveTopology = D3D10_DST_IA_PRIMITIVE_TOPOLOGY,
	RasterizerStateViewPort = D3D10_DST_RS_VIEWPORTS,
	RasterizerScissorRectangle = D3D10_DST_RS_SCISSOR_RECTS,
	RasterizerState = D3D10_DST_RS_RASTERIZER_STATE,
	Predication = D3D10_DST_PREDICATION
};


public enum class DSV_Dimension
{
	Unknown = D3D10_DSV_DIMENSION_UNKNOWN,
	Texture1D = D3D10_DSV_DIMENSION_TEXTURE1D ,
	Texture1DArray = D3D10_DSV_DIMENSION_TEXTURE1DARRAY,
	Texture2D = D3D10_DSV_DIMENSION_TEXTURE2D,
	Texture2DArray = D3D10_DSV_DIMENSION_TEXTURE2DARRAY,
	Texture2DMS = D3D10_DSV_DIMENSION_TEXTURE2DMS,
	Texture2DMSArray = D3D10_DSV_DIMENSION_TEXTURE2DMSARRAY
};

public enum class DriverType
{	
	Hardware = D3D10_DRIVER_TYPE_HARDWARE,
	Reference = D3D10_DRIVER_TYPE_REFERENCE,
	Null = D3D10_DRIVER_TYPE_NULL,
	Software = D3D10_DRIVER_TYPE_SOFTWARE,
	Warp = D3D10_DRIVER_TYPE_WARP
};

[System::Flags]
public enum class EffectFlag
{
	CompileChildEffect = D3D10_EFFECT_COMPILE_CHILD_EFFECT,
	CompileAllowSlowOperations = D3D10_EFFECT_COMPILE_ALLOW_SLOW_OPS,
	SingleThreaded = D3D10_EFFECT_SINGLE_THREADED,
	VariableAnnotation = D3D10_EFFECT_VARIABLE_ANNOTATION,
	VariablePooled = D3D10_EFFECT_VARIABLE_POOLED,
	VariableExplicitBindPoint = D3D10_EFFECT_VARIABLE_EXPLICIT_BIND_POINT
};

public enum class Error
{
	FileNotFound = D3D10_ERROR_FILE_NOT_FOUND,
	TooManyUniqueStateObjects = D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS,
	InvalidCall = D3DERR_INVALIDCALL,
	WasStillDrawing = D3DERR_WASSTILLDRAWING,
};

public enum class FillMode
{
	Wireframe = D3D10_FILL_WIREFRAME,
	Solid = D3D10_FILL_SOLID
};

public enum class Filter
{
	MinificationMagnificationMipPoint = D3D10_FILTER_MIN_MAG_MIP_POINT,
	MinificationMagnificationPointMipLinear = D3D10_FILTER_MIN_MAG_POINT_MIP_LINEAR,
	MinificationPointMagnificationLinearMipPoint = D3D10_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT,
	MinificationPointMagnificationMipLinear = D3D10_FILTER_MIN_POINT_MAG_MIP_LINEAR,
	MinificationLinearMagnificationMipPoint = D3D10_FILTER_MIN_LINEAR_MAG_MIP_POINT,
	MinificationLinearMaginificationPointMipLinear = D3D10_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
	MinificationMagnificationLinearMipPoint = D3D10_FILTER_MIN_MAG_LINEAR_MIP_POINT,
	MinificationMagnificationMipLinear = D3D10_FILTER_MIN_MAG_MIP_LINEAR,
	Anisotropic = D3D10_FILTER_ANISOTROPIC,
	ComparisonMinificationMagnificationMipPoint = D3D10_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
	ComparisonMinificationMagnificationPointMipLinear = D3D10_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR,
	ComparisonMinificationPointMagnificationLinearMipPoint = D3D10_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT,
	ComparisonMinificationPointMagnificationMipLinear = D3D10_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR,
	ComparisonMinificationLinearMagnificationMipPoint = D3D10_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT,
	ComparisonMinificationLinearMagnificationPointMipLinear = D3D10_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
	ComparisonMinificationMagnificationLinearMipPoint = D3D10_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT,
	ComparisonMinificationMagnificationMipLinear = D3D10_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
	ComparisonAnisotropic = D3D10_FILTER_COMPARISON_ANISOTROPIC,
	Text1Bit = D3D10_FILTER_TEXT_1BIT 
};

public enum class FilterType
{
	Point = D3D10_FILTER_TYPE_POINT,
	Linear = D3D10_FILTER_TYPE_LINEAR 
};

public enum class FormatSupport
{
	Buffer = D3D10_FORMAT_SUPPORT_BUFFER,
	InputAssemblerVertexBuffer = D3D10_FORMAT_SUPPORT_IA_VERTEX_BUFFER,
	InputAssemblerIndexBuffer = D3D10_FORMAT_SUPPORT_IA_INDEX_BUFFER,
	StreamingOutputBuffer = D3D10_FORMAT_SUPPORT_SO_BUFFER,
	Texture1D = D3D10_FORMAT_SUPPORT_TEXTURE1D,
	Texture2D = D3D10_FORMAT_SUPPORT_TEXTURE2D,
	Texture3D = D3D10_FORMAT_SUPPORT_TEXTURE3D,
	Texturecube = D3D10_FORMAT_SUPPORT_TEXTURECUBE,
	ShaderLoad = D3D10_FORMAT_SUPPORT_SHADER_LOAD,
	ShaderSample = D3D10_FORMAT_SUPPORT_SHADER_SAMPLE,
	ShaderSampleComparison = D3D10_FORMAT_SUPPORT_SHADER_SAMPLE_COMPARISON,
	ShaderSampleMonoText = D3D10_FORMAT_SUPPORT_SHADER_SAMPLE_MONO_TEXT,
	Mipmap = D3D10_FORMAT_SUPPORT_MIP,
	MipmapAutoGeneration = D3D10_FORMAT_SUPPORT_MIP_AUTOGEN,
	RenderTarget = D3D10_FORMAT_SUPPORT_RENDER_TARGET,
	Blendable = D3D10_FORMAT_SUPPORT_BLENDABLE,
	DepthStencil = D3D10_FORMAT_SUPPORT_DEPTH_STENCIL,
	CPU_Lockable = D3D10_FORMAT_SUPPORT_CPU_LOCKABLE,
	MultisampleResolve = D3D10_FORMAT_SUPPORT_MULTISAMPLE_RESOLVE,
	Display = D3D10_FORMAT_SUPPORT_DISPLAY,
	CastWithinBitLayout = D3D10_FORMAT_SUPPORT_CAST_WITHIN_BIT_LAYOUT,
	MultisampleRenderTarget = D3D10_FORMAT_SUPPORT_MULTISAMPLE_RENDERTARGET,
	MultisampleLoad = D3D10_FORMAT_SUPPORT_MULTISAMPLE_LOAD,
	ShaderGather = D3D10_FORMAT_SUPPORT_SHADER_GATHER
};

public enum class IA
{
	DefaultIndexBufferOffsetInBytes = D3D10_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES,
	DefaultPrimitiveTopology = D3D10_IA_DEFAULT_PRIMITIVE_TOPOLOGY,
	DefaultVertexBufferOffsetInBytes = D3D10_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES,
	IndexInputResourceSlotCount = D3D10_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT,
	InstanceIdBitCount = D3D10_IA_INSTANCE_ID_BIT_COUNT,
	IntegerArithmeticBitCount = D3D10_IA_INTEGER_ARITHMETIC_BIT_COUNT,
	PrimitiveIdBitCount = D3D10_IA_PRIMITIVE_ID_BIT_COUNT,
	VertexIdBitCount = D3D10_IA_VERTEX_ID_BIT_COUNT,
	VertexInputResourceSlotCount = D3D10_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT,
	VertexInputStructureElementsComponents = D3D10_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS,
	VertexInputStructureElementCount = D3D10_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT
};

public enum class IncludeType
{
	Local = D3D10_INCLUDE_LOCAL,
	System = D3D10_INCLUDE_SYSTEM,
	ForceDWORD = D3D10_INCLUDE_FORCE_DWORD
};

public enum class InputClassification
{	
	InputPerVertexData = D3D10_INPUT_PER_VERTEX_DATA,
	InputPerInstanceData = D3D10_INPUT_PER_INSTANCE_DATA,
};

public enum class Map
{
	Read = D3D10_MAP_READ,
	Write = D3D10_MAP_WRITE,
	ReadWrite = D3D10_MAP_READ_WRITE,
	Discard = D3D10_MAP_WRITE_DISCARD,
	NoOverwrite = D3D10_MAP_WRITE_NO_OVERWRITE 
};

[System::Flags]
public enum class MapFlag
{
	DoNotWait = D3D10_MAP_FLAG_DO_NOT_WAIT 
};

public enum class MessageID
{
	Unknown = D3D10_MESSAGE_ID_UNKNOWN,
	DeviceIA_SetVertexBufferHazard = D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_HAZARD, 
	DeviceIA_SetIndexBufferHazard = D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_HAZARD,
	DeviceVertexShader_SetShaderResourceHazard = D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_HAZARD,
	DeviceVertexShader_SetConstantBufferHazard = D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_HAZARD,
	DeviceGeometryShader_SetShaderResourceHazard = D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_HAZARD,
	DeviceGeometryShader_SetConstantBuffersHazard = D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_HAZARD,
	DevicePixelShader_SetResourcesHazard = D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_HAZARD,
	DevicePixelShader_SetConstantBufferHazard = D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_HAZARD,
	DeviceOM_SetRenderTargetHazard = D3D10_MESSAGE_ID_DEVICE_OMSETRENDERTARGETS_HAZARD,
	DeviceSO_SetTargetHazard = D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_HAZARD,
	StringFromApplication = D3D10_MESSAGE_ID_STRING_FROM_APPLICATION,
	CorruptedThis = D3D10_MESSAGE_ID_CORRUPTED_THIS,
	CorruptedParameter1 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER1,
	CorruptedParameter2 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER2,
	CorruptedParameter3 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER3,
	CorruptedParameter4 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER4,
	CorruptedParameter5 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER5,
	CorruptedParameter6 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER6,
	CorruptedParameter7 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER7,
	CorruptedParameter8 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER8,
	CorruptedParameter9 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER9,
	CorruptedParameter10 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER10,
	CorruptedParameter11 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER11,
	CorruptedParameter12 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER12,
	CorruptedParameter13 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER13,
	CorruptedParameter14 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER14,
	CorruptedParameter15 = D3D10_MESSAGE_ID_CORRUPTED_PARAMETER15,
	CorruptedMultiThreading = D3D10_MESSAGE_ID_CORRUPTED_MULTITHREADING,
	MessageReportingOutOfMemory = D3D10_MESSAGE_ID_MESSAGE_REPORTING_OUTOFMEMORY,
	IA_SetInputLayoutUnbindDeletingObject = D3D10_MESSAGE_ID_IASETINPUTLAYOUT_UNBINDDELETINGOBJECT,
	IA_SetVertexBufferUnbindDeletingObject = D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT,
	IA_SetIndexBufferUnbindDeletingObject = D3D10_MESSAGE_ID_IASETINDEXBUFFER_UNBINDDELETINGOBJECT,
	VertexShaderSetShaderUnbindDeletingObject = D3D10_MESSAGE_ID_VSSETSHADER_UNBINDDELETINGOBJECT,
	VertexShaderSetShaderResourceUnbindDeletingObject = D3D10_MESSAGE_ID_VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT,
	VertexShaderSetConstantBufferUnbindDeletingObject = D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT,
	VertexShaderSetSamplersUnbindDeletingObject = D3D10_MESSAGE_ID_VSSETSAMPLERS_UNBINDDELETINGOBJECT,
	GeometryShaderSetShaderUnbindDeletingObject = D3D10_MESSAGE_ID_GSSETSHADER_UNBINDDELETINGOBJECT,
	GeometryShaderSetShaderResourceUnbindDeletingObject = D3D10_MESSAGE_ID_GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT,
	GeometryShaderSetConstantBufferUnbindDeletingObject = D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT,
	GeometryShaderSetSamplerUnbindDeletingObject = D3D10_MESSAGE_ID_GSSETSAMPLERS_UNBINDDELETINGOBJECT,
	SO_SetTargetsUnbindDeletingObject = D3D10_MESSAGE_ID_SOSETTARGETS_UNBINDDELETINGOBJECT,
	PixelShaderSetShaderUnbindDeletingObject = D3D10_MESSAGE_ID_PSSETSHADER_UNBINDDELETINGOBJECT,
	PixelShaderSetShaderResourceUnbindDeletingObject = D3D10_MESSAGE_ID_PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT,
	PixelShaderSetConstantBufferUnbindDeletingObject = D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT,
	PixelShaderSetSamplerUnbindDeletingObject = D3D10_MESSAGE_ID_PSSETSAMPLERS_UNBINDDELETINGOBJECT,
	RS_SetStateUnbindDeletingObject = D3D10_MESSAGE_ID_RSSETSTATE_UNBINDDELETINGOBJECT,
	OM_SetBlendStateUnbindDeletingObject = D3D10_MESSAGE_ID_OMSETBLENDSTATE_UNBINDDELETINGOBJECT,
	OM_SetDepthStencilStateUnbindDeletingObject = D3D10_MESSAGE_ID_OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT,
	OM_SetRenderTargetUnBindDeletingObject = D3D10_MESSAGE_ID_OMSETRENDERTARGETS_UNBINDDELETINGOBJECT,
	SetPredicationUnbindDeletingObject = D3D10_MESSAGE_ID_SETPREDICATION_UNBINDDELETINGOBJECT,
	GetPrivateDataMoreData = D3D10_MESSAGE_ID_GETPRIVATEDATA_MOREDATA,
	SetPrivateDataInvalidFreeData =  D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFREEDATA,
	SetPrivateDataInvalidUnknown = D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDIUNKNOWN,
	SetPrivateDataInvalidFlags = D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFLAGS,
	SetPrivateDataChangingParams = D3D10_MESSAGE_ID_SETPRIVATEDATA_CHANGINGPARAMS,
	SetPrivateDataOutOfMemory = D3D10_MESSAGE_ID_SETPRIVATEDATA_OUTOFMEMORY,
	CreateBufferUnrecognizedFormat = D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDFORMAT,
	CreateBufferInvalidSampler = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDSAMPLES,
	CreateBufferUnrecognizedUsage = D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDUSAGE,
	CreateBufferUnrecognizedBindFlags = D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDBINDFLAGS,
	CreateBufferUnrecognizedCPU_AccessFlags = D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS,
	CreateBufferUnRecognizedMiscellaneousFlags = D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDMISCFLAGS,
	CreateBufferInvalidCPU_AccessFlags = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCPUACCESSFLAGS,
	CreateBufferInvalidBindFlags = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDBINDFLAGS,
	CreateBufferInvalidInitialData = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDINITIALDATA,
	CreateBufferInvalidDimensions = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDDIMENSIONS,
	CreateBufferInvalidMipLevel = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMIPLEVELS,
	CreateBufferInvalidMiscellaneousFlags = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMISCFLAGS,
	CreateBufferInvalidArgumentReturn = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDARG_RETURN,
	CreateBufferOutOfMemoryReturn = D3D10_MESSAGE_ID_CREATEBUFFER_OUTOFMEMORY_RETURN,
	CreateBufferNullDescription = D3D10_MESSAGE_ID_CREATEBUFFER_NULLDESC,
	CreateBufferInvalidConstantBufferBindings = D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS,
	CreateBufferLargeAllocation = D3D10_MESSAGE_ID_CREATEBUFFER_LARGEALLOCATION,
	CreateTexture1D_UnrecognizedFormat = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDFORMAT,
	CreateTexture1D_UnSupportedFormat = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNSUPPORTEDFORMAT,
	CreateTexture1D_InvalidSampler = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDSAMPLES,
	CreateTexture1D_UnrecognizedUsage = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDUSAGE,
	CreateTexture1D_UnrecognizedBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS,
	CreateTexture1D_UnrecognizedCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS,
	CreateTexture1D_UnrecognizedMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS,
	CreateTexture1D_InvalidCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDCPUACCESSFLAGS,
	CreateTexture1D_InvalidBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDBINDFLAGS,
	CreateTexture1D_InvalidInitialData = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDINITIALDATA,
	CreateTexture1D_InvalidDimension = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDDIMENSIONS,
	CreateTexture1D_InvalidMipLevels = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMIPLEVELS,
	CreateTexture1D_InvalidMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMISCFLAGS,
	CreateTexture1D_InvalidArgumentReturn = D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDARG_RETURN,
	CreateTexture1D_OutofMemoryReturn = D3D10_MESSAGE_ID_CREATETEXTURE1D_OUTOFMEMORY_RETURN,
	CreateTexture1D_NullDescription = D3D10_MESSAGE_ID_CREATETEXTURE1D_NULLDESC,
	CreateTexture1D_LargeAllocation = D3D10_MESSAGE_ID_CREATETEXTURE1D_LARGEALLOCATION,	
	CreateTexture2D_UnrecognizedFormat = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDFORMAT,
	CreateTexture2D_UnSupportedFormat = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNSUPPORTEDFORMAT,
	CreateTexture2D_InvalidSampler = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDSAMPLES,
	CreateTexture2D_UnrecognizedUsage = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDUSAGE,
	CreateTexture2D_UnrecognizedBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS,
	CreateTexture2D_UnrecognizedCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS,
	CreateTexture2D_UnrecognizedMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS,
	CreateTexture2D_InvalidCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDCPUACCESSFLAGS,
	CreateTexture2D_InvalidBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDBINDFLAGS,
	CreateTexture2D_InvalidInitialData = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDINITIALDATA,
	CreateTexture2D_InvalidDimension = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS,
	CreateTexture2D_InvalidMipLevels = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMIPLEVELS,
	CreateTexture2D_InvalidMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMISCFLAGS,
	CreateTexture2D_InvalidArgumentReturn = D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDARG_RETURN,
	CreateTexture2D_OutofMemoryReturn = D3D10_MESSAGE_ID_CREATETEXTURE2D_OUTOFMEMORY_RETURN,
	CreateTexture2D_NullDescription = D3D10_MESSAGE_ID_CREATETEXTURE2D_NULLDESC,
	CreateTexture2D_LargeAllocation = D3D10_MESSAGE_ID_CREATETEXTURE2D_LARGEALLOCATION,
	CreateTexture3D_UnrecognizedFormat = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDFORMAT,
	CreateTexture3D_UnSupportedFormat = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNSUPPORTEDFORMAT,
	CreateTexture3D_InvalidSampler = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDSAMPLES,
	CreateTexture3D_UnrecognizedUsage = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDUSAGE,
	CreateTexture3D_UnrecognizedBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS,
	CreateTexture3D_UnrecognizedCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS,
	CreateTexture3D_UnrecognizedMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS,
	CreateTexture3D_InvalidCPU_AccessFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDCPUACCESSFLAGS,
	CreateTexture3D_InvalidBindFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDBINDFLAGS,
	CreateTexture3D_InvalidInitialData = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDINITIALDATA,
	CreateTexture3D_InvalidDimension = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDDIMENSIONS,
	CreateTexture3D_InvalidMipLevels = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMIPLEVELS,
	CreateTexture3D_InvalidMiscellaneousFlags = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMISCFLAGS,
	CreateTexture3D_InvalidArgumentReturn = D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDARG_RETURN,
	CreateTexture3D_OutofMemoryReturn = D3D10_MESSAGE_ID_CREATETEXTURE3D_OUTOFMEMORY_RETURN,
	CreateTexture3D_NullDescription = D3D10_MESSAGE_ID_CREATETEXTURE3D_NULLDESC,
	CreateTexture3D_LargeAllocation = D3D10_MESSAGE_ID_CREATETEXTURE3D_LARGEALLOCATION,
	CreateShaderResourceViewUnrecognizedFormat = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT, 
	CreateShaderResourceViewInvalidDescription = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDESC, 
	CreateShaderResourceViewInvalidFormat = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFORMAT, 
	CreateShaderResourceViewInvalidDimension = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS,
	CreateShaderResourceViewInvalidResource = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDRESOURCE,
	CreateShaderResourceViewTooManyObjects = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS, 
	CreateShaderResourceViewInvalidArgumentReturn = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN,
	CreateShaderResourceViewOutOfMemoryReturn = D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN,
	CreateRenderTargetViewUnrecognizedFormat = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT, 
	CreateRenderTargetViewInvalidDescription = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDESC, 
	CreateRenderTargetViewInvalidFormat = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDFORMAT, 
	CreateRenderTargetViewInvalidDimension = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDIMENSIONS,
	CreateRenderTargetViewInvalidResource = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDRESOURCE,
	CreateRenderTargetViewTooManyObjects = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_TOOMANYOBJECTS, 
	CreateRenderTargetViewInvalidArgumentReturn = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDARG_RETURN,
	CreateRenderTargetViewOutOfMemoryReturn = D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN,
	CreateDepthStencilViewUnrecognizedFormat = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT, 
	CreateDepthStencilInvalidDescription = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDESC, 
	CreateDepthStencilInvalidFormat =  D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFORMAT, 
	CreateDepthStencilInvalidDimension = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS, 
	CreateDepthStencilInvalidResource = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE, 
	CreateDepthStencilTooManyObjects = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS, 
	CreateDepthStencilInvalidArgumentReturn =  D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN, 
	CreateDepthStencilOutOfMemoryReturn = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN, 
	CreateInputLayoutOutOfMemory = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_OUTOFMEMORY,
	CreateInputLayoutTooManyElements = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TOOMANYELEMENTS, 
	CreateInputLayoutInvalidFormat = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDFORMAT, 
	CreateInputLayoutIncompatibleFormat = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT, 
	CreateInputLayoutInvalidSlot = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOT, 
	CreateInputLayoutInvalidInputSlotClass = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS, 
	CreateInputLayoutStepRateSlotClassMismatch = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH, 
	CreateInputLayoutInvalidSlotClassChange = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE, 
	CreateInputLayoutInvalidStepRateChange = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE, 
	CreateInputLayoutInvalidAlingment = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDALIGNMENT, 
	CreateInputLayoutDuplicateSenmatic = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_DUPLICATESEMANTIC, 
	CreateInputLayoutUnparseableInputSignature = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE, 
	CreateInputLayoutNullSemantic = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLSEMANTIC, 
	CreateInputLayoutMissingElement = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_MISSINGELEMENT, 
	CreateInputLayoutNullDescription = D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLDESC,
	CreateVertexShaderOutOfMemory = D3D10_MESSAGE_ID_CREATEVERTEXSHADER_OUTOFMEMORY, 
	CreateVertexShaderInvalidShaderByteCode = D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERBYTECODE,
	CreateVertexShaderInvalidShaderType = D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERTYPE, 
	CreateGeometryShaderOutOfMemory = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_OUTOFMEMORY, 
	CreateGeometryShaderInvalidShaderByteCode = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE,
	CreateGeometryShaderInvalidShaderType = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERTYPE,
	CreateGeomertyShaderWithStreamOutput_OutOfMemory = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY, 
	CreateGeomertyShaderWithStreamOutput_InvalidShaderByteCode = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE, 
	CreateGeomertyShaderWithStreamOutput_InvalidShaderType = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE, 
	CreateGeomertyShaderWithStreamOutput_InvalidNumentries = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES, 
	CreateGeomertyShaderWithStreamOutput_OutputStreamTrideUnused = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED, 
	CreateGeomertyShaderWithStreamOutput_UnexpectedDeclaration = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL, 
	CreateGeomertyShaderWithStreamOutput_ExpectedDeclaration = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL, 
	CreateGeomertyShaderWithStreamOutput_OutPutSlot0Expected = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED, 
	CreateGeomertyShaderWithStreamOutput_InvalidOutputSlot = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT, 
	CreateGeomertyShaderWithStreamOutput_OnlyOneElementPerSlot = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT, 
	CreateGeomertyShaderWithStreamOutput_InvalidComponentCount = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT, 
	CreateGeomertyShaderWithStreamOutput_InvalidStartComponentAndComponentCount = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT, 
	CreateGeomertyShaderWithStreamOutput_InvalidGapDefinition = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION, 
	CreateGeomertyShaderWithStreamOutput_RepeatOutput = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT, 
	CreateGeomertyShaderWithStreamOutput_InvalidOutputStreamStride = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE, 
	CreateGeomertyShaderWithStreamOutput_MissingSemantic = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC, 
	CreateGeomertyShaderWithStreamOutput_MaskMismatch = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH, 
	CreateGeomertyShaderWithStreamOutput_CantHaveOnlyGaps = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS, 
	CreateGeomertyShaderWithStreamOutput_DeclarationTooComplex = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX, 
	CreateGeomertyShaderWithStreamOutput_MissingOutputSignature = D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE,
	CreatePixelShaderOutofMemory = D3D10_MESSAGE_ID_CREATEPIXELSHADER_OUTOFMEMORY, 
	CreatePixelShaderInvalidShaderByteCode = D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERBYTECODE, 
	CreatePixelShaderInvalidShaderType = D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERTYPE,
	CreateRasterizerStateInvalidFillMode = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDFILLMODE, 
	CreateRasterizerStateInvalidCullMode = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDCULLMODE,
	CreateRasterizerStateInvalidDepthbiasClamp = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP,
	CreateRasterizerStateInvalidSlopecaledDepthbias = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS, 
	CreateRasterizerStateTooManyObjects = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_TOOMANYOBJECTS, 
	CreateRasterizerStateNullDescription = D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_NULLDESC,
	CreateDepthStencilStateInvalidDepthWriteMask = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK,
	CreateDepthStencilStateInvalidDepthFunction = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC, 
	CreateDepthStencilStateInvalidFrontFaceStencilFailOperation = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP, 
	CreateDepthStencilStateInvalidFrontFaceStencilZ_FailOpreation = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP, 
	CreateDepthStencilStateInvalidFrontFaceStencilPassOperation = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP, 
	CreateDepthStencilStateInvalidFrontFaceStencilFunction = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC, 
	CreateDepthStencilStateInvalidBackFaceStencilFailOperation = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP, 
	CreateDepthStencilStateInvalidBackFaceStencilZ_FailOpreation  = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP, 
	CreateDepthStencilStateInvalidBackFaceStencilPassOperation = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP, 
	CreateDepthStencilStateInvalidBackFaceStencilFunction = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC, 
	CreateDepthStencilStateTooManyObjects = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS, 
	CreateDepthStencilStateNullDescription = D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_NULLDESC,
	CreateBlendStateInvalidSourceBlend = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLEND, 
	CreateBlendStateInvalidDestinationBlend = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLEND, 
	CreateBlendStateInvalidBlendOperation = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOP, 
	CreateBlendStateInvalidBlendAlpha = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLENDALPHA, 
	CreateBlendStateInvalidDestinationBlendAlpha = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLENDALPHA, 
	CreateBlendStateInvalidBlendOperationAlpha = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOPALPHA, 
	CreateBlendStateInvalidRenderTargetWriteMask = D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK, 
	CreateBlendStateTooManyObjects = D3D10_MESSAGE_ID_CREATEBLENDSTATE_TOOMANYOBJECTS, 
	CreateBlendStateNullDescription = D3D10_MESSAGE_ID_CREATEBLENDSTATE_NULLDESC,
	CreateSamplerStateInvalidFilter = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDFILTER, 
	CreateSamplerStateInvalidAddressU = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSU, 
	CreateSamplerStateInvalidAddressV = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSV, 
	CreateSamplerStateInvalidAddressW = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSW, 
	CreateSamplerStateInvalidMipLodBias = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMIPLODBIAS, 
	CreateSamplerStateInvalidMaxAnisotropy = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXANISOTROPY, 
	CreateSamplerStateInvalidComparisonFunction = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC,
	CreateSamplerStateInvalidMinLod = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMINLOD, 
	CreateSamplerStateInvalidMaxLod = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXLOD, 
	CreateSamplerStateTooManyObjects = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_TOOMANYOBJECTS, 
	CreateSamplerStateNullDescription  = D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NULLDESC,
	CreateQueryPredicateInvalidQuery = D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDQUERY, 
	CreateQueryPredicateInvalidMiscellaneousFlags = D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDMISCFLAGS, 
	CreateQueryPredicateUnexpectedMiscellaneousFlags = D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG, 
	CreateQueryPredicateNullDescription = D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_NULLDESC,
	DeviceIA_SetPrimitiveTopology_TopologyUnrecognized = D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED, 
	DeviceIA_SetPrimitiveTopology_TopologyUndefined = D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED,
	IA_SetVertexBufferInvalidBuffer = D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_INVALIDBUFFER,
	DeviceIA_SetVertexBufferOffsetTooLarge = D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE,
	DeviceIA_SetVertexBuffer_BufferEmpty = D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY,
	IA_SetIndexBufferInvalidBuffer = D3D10_MESSAGE_ID_IASETINDEXBUFFER_INVALIDBUFFER,
	DeviceIA_SetIndexBufferFormatInvalid = D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_FORMAT_INVALID, 
	DeviceIA_SetIndexBufferOffsetTooLarge = D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE, 
	DeviceIA_SetIndexBufferOffsetUnaligned = D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED, 
	DeviceVertexShaderSetShaderResourceViewsEmpty = D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY,
	VertexShaderConstantBufferInvalidBuffer = D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_INVALIDBUFFER,
	DeviceVertexShaderSetConstantBufferBuffersEmpty = D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY, 
	DeviceVertexShaderSetSamplerSamplersEmpty = D3D10_MESSAGE_ID_DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY, 	
	DeviceGeomertyShader_ResourcesViewEmpty = D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY,
	GeometryShaderSetConstantBufferInvalidBuffer = D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_INVALIDBUFFER,
	DeviceGeometryShader_SetConstantBufferEmpty =D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY,
	DeviceGeometryShader_SetSamplerSamplerEmpty =D3D10_MESSAGE_ID_DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY,
	SO_SetTargetInvalidBuffer = D3D10_MESSAGE_ID_SOSETTARGETS_INVALIDBUFFER,
	DeviceSO_SetTargetOffsetUnaligned = D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_OFFSET_UNALIGNED,
	DevicePixelShader_SetShaderResourcesViewEmpty = D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY,
	PixelShaderConstantBufferInvalidBuffer = D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_INVALIDBUFFER,	
	DevicePixelShader_SetConstantBufferBuffersEmpty = D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY, 
	DevicePixelShader_SetSamplersEmpty = D3D10_MESSAGE_ID_DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY, 
	DeviceRS_SetInvalidViewPort = D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT, 
	DeviceRS_SetInvalidScissor = D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR,
	ClearRenderTargetViewDenormFlush = D3D10_MESSAGE_ID_CLEARRENDERTARGETVIEW_DENORMFLUSH,
	ClearDepthStencilViewDenormFlush = D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DENORMFLUSH,
	ClearDepthStencilViewInvalid = D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_INVALID,







};

public enum class MessageCategory
{
	ApplicationDefined = D3D10_MESSAGE_CATEGORY_APPLICATION_DEFINED,
	Miscellaneous = D3D10_MESSAGE_CATEGORY_MISCELLANEOUS,
	Initialization = D3D10_MESSAGE_CATEGORY_INITIALIZATION,
	Cleanup = D3D10_MESSAGE_CATEGORY_CLEANUP,
	Compilation = D3D10_MESSAGE_CATEGORY_COMPILATION,
	StateCreation = D3D10_MESSAGE_CATEGORY_STATE_CREATION,
	StateSetting = D3D10_MESSAGE_CATEGORY_STATE_SETTING,
	StateGetting = D3D10_MESSAGE_CATEGORY_STATE_GETTING,
	ResourceManipulation = D3D10_MESSAGE_CATEGORY_RESOURCE_MANIPULATION,
	Execution = D3D10_MESSAGE_CATEGORY_EXECUTION
};

public enum class MessageSeverity
{
	Corruption = D3D10_MESSAGE_SEVERITY_CORRUPTION,
	Error = D3D10_MESSAGE_SEVERITY_ERROR,
	Warning = D3D10_MESSAGE_SEVERITY_WARNING,
	Info = D3D10_MESSAGE_SEVERITY_INFO
};

public enum class Primitive
{
	Undefined = D3D10_PRIMITIVE_UNDEFINED,
	Point = D3D10_PRIMITIVE_POINT,
	Line = D3D10_PRIMITIVE_LINE,
	Triangle = D3D10_PRIMITIVE_TRIANGLE,
	LineAdject = D3D10_PRIMITIVE_LINE_ADJ,
	TriangeAdject = D3D10_PRIMITIVE_TRIANGLE_ADJ
};

public enum class PrimitiveTopology
{
	Undefined = D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED,
	PointList = D3D10_PRIMITIVE_TOPOLOGY_POINTLIST,
	LineList = D3D10_PRIMITIVE_TOPOLOGY_LINELIST,
	LineStrip = D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP,
	TriangleList = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
	TriangleStrip = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
	LineListAdjacency = D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
	LineStripAdjacency = D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
	TriangleListAdjacency = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
	TriangleStripAdjacency = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
};

public enum class Query
{
	Event = D3D10_QUERY_EVENT,
	Occlusion = D3D10_QUERY_OCCLUSION,
	Timestamp = D3D10_QUERY_TIMESTAMP,
	TimesampDisjoint = D3D10_QUERY_TIMESTAMP_DISJOINT,
	PipelineStatistics = D3D10_QUERY_PIPELINE_STATISTICS,
	OcclusionPredicate = D3D10_QUERY_OCCLUSION_PREDICATE,
	SteamingOutStatistics = D3D10_QUERY_SO_STATISTICS,
	StreamingOutOverflowPredicate = D3D10_QUERY_SO_OVERFLOW_PREDICATE
};

[System::Flags]
public enum class QueryMiscellaneousFlag
{
	Predicatehint = D3D10_QUERY_MISC_PREDICATEHINT
};

[System::Flags]
public enum class RaiseFlag
{
	DriverInternalError = D3D10_RAISE_FLAG_DRIVER_INTERNAL_ERROR
};

public enum class RegisterComponentType
{
	Unknown = D3D10_REGISTER_COMPONENT_UNKNOWN,
	UInt32 = D3D10_REGISTER_COMPONENT_UINT32,
	SInt32 = D3D10_REGISTER_COMPONENT_SINT32,
	Float32 = D3D10_REGISTER_COMPONENT_FLOAT32
};



public enum class ResourceDimension
{
	Unknown = D3D10_RESOURCE_DIMENSION_UNKNOWN,
	Buffer = D3D10_RESOURCE_DIMENSION_BUFFER,
	Texture1D = D3D10_RESOURCE_DIMENSION_TEXTURE1D,
	Texture2D = D3D10_RESOURCE_DIMENSION_TEXTURE2D,
	Texture3D = D3D10_RESOURCE_DIMENSION_TEXTURE3D
};

[System::Flags]
public enum class ResourceMiscFlag
{
	GenerateMips = D3D10_RESOURCE_MISC_GENERATE_MIPS,
	Shared = D3D10_RESOURCE_MISC_SHARED,
	TextureCube = D3D10_RESOURCE_MISC_TEXTURECUBE,
	SharedKeyedMutex = D3D10_RESOURCE_MISC_SHARED_KEYEDMUTEX,
	GDI_Compatible = D3D10_RESOURCE_MISC_GDI_COMPATIBLE
};

public enum class ResourceReturnType
{
	Unorm = D3D10_RETURN_TYPE_UNORM,
	Snorm = D3D10_RETURN_TYPE_SNORM,
	SInt = D3D10_RETURN_TYPE_SINT,
	UInt = D3D10_RETURN_TYPE_UINT,
	Float = D3D10_RETURN_TYPE_FLOAT,
	Mixed = D3D10_RETURN_TYPE_MIXED
};

public enum class Requirement
{
	BlendObjectCountPerCentext = D3D10_REQ_BLEND_OBJECT_COUNT_PER_CONTEXT,
	BufferResourceTexelCount2ToExp = D3D10_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP,	
	ConstantBufferElementCount = D3D10_REQ_CONSTANT_BUFFER_ELEMENT_COUNT,
	DepthStencilObjectCountPerContext = D3D10_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_CONTEXT,	
	DrawIndexedIndexCount2ToExp = D3D10_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP,
	DrawVertexCount2ToExp = D3D10_REQ_DRAW_VERTEX_COUNT_2_TO_EXP,
	FilteringHW_AddressableResourceDimension = D3D10_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION,	
	GeometyShaderInvocation32BitOutputComponentLimit = D3D10_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT,	
	ImmediateConstantBufferElementCount = D3D10_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT,
	MaxAnisotropy = D3D10_REQ_MAXANISOTROPY,
	MipLevels = D3D10_REQ_MIP_LEVELS,
	MultiElementStructureSizeInBytes = D3D10_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES,	
	RasterizerObjectCountPerContext = D3D10_REQ_RASTERIZER_OBJECT_COUNT_PER_CONTEXT,	
	RenderToBufferWindowWidth = D3D10_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH,	
	ResourceSizeInMegabytes = D3D10_REQ_RESOURCE_SIZE_IN_MEGABYTES,
	ResourceViewCountPerContext2ToExp = D3D10_REQ_RESOURCE_VIEW_COUNT_PER_CONTEXT_2_TO_EXP,	
	SamplerObjectCountPerContext = D3D10_REQ_SAMPLER_OBJECT_COUNT_PER_CONTEXT,	
	Texture1D_ArrayAxisDimension = D3D10_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION,
	Texture1D_U_Dimension = D3D10_REQ_TEXTURE1D_U_DIMENSION,
	Texture2D_ArrayAxisDimension = D3D10_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION,
	Texture2D_U_OrV_Dimension = D3D10_REQ_TEXTURE2D_U_OR_V_DIMENSION,	
	Texture3D_U_V_OrW_Dimension = D3D10_REQ_TEXTURE3D_U_V_OR_W_DIMENSION,	
	TextureCubeDimension = D3D10_REQ_TEXTURECUBE_DIMENSION,
};

public enum class RTV_Dimension
{
	Unknown = D3D10_RTV_DIMENSION_UNKNOWN,
	Buffer = D3D10_RTV_DIMENSION_BUFFER,
	Texture1D = D3D10_RTV_DIMENSION_TEXTURE1D ,
	Texture1DArray = D3D10_RTV_DIMENSION_TEXTURE1DARRAY,
	Texture2D = D3D10_RTV_DIMENSION_TEXTURE2D,
	Texture2DArray = D3D10_RTV_DIMENSION_TEXTURE2DARRAY,
	Texture2DMS = D3D10_RTV_DIMENSION_TEXTURE2DMS,
	Texture2DMSArray = D3D10_RTV_DIMENSION_TEXTURE2DMSARRAY,
	Texture3D = D3D10_RTV_DIMENSION_TEXTURE3D
};

public enum class SRV_Dimension
{
	Unknown = D3D10_SRV_DIMENSION_UNKNOWN,
	Buffer = D3D10_SRV_DIMENSION_BUFFER,
	Texture1D = D3D10_SRV_DIMENSION_TEXTURE1D ,
	Texture1DArray = D3D10_SRV_DIMENSION_TEXTURE1DARRAY,
	Texture2D = D3D10_SRV_DIMENSION_TEXTURE2D,
	Texture2DArray = D3D10_SRV_DIMENSION_TEXTURE2DARRAY,
	Texture2DMS = D3D10_SRV_DIMENSION_TEXTURE2DMS,
	Texture2DMSArray = D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY,
	Texture3D = D3D10_SRV_DIMENSION_TEXTURE3D,
	TextureCube = D3D10_SRV_DIMENSION_TEXTURECUBE
};

public enum class StencilOperation
{
	Keep = D3D10_STENCIL_OP_KEEP,
	Zero = D3D10_STENCIL_OP_ZERO,
	Replace = D3D10_STENCIL_OP_REPLACE,
	IncrementSaturate = D3D10_STENCIL_OP_INCR_SAT,
	DecrementSaturate = D3D10_STENCIL_OP_DECR_SAT,
	Invert = D3D10_STENCIL_OP_INVERT,
	Increment = D3D10_STENCIL_OP_INCR,
	Decrement = D3D10_STENCIL_OP_DECR
};

[System::Flags]
public enum class ShaderFlag
{
	Debug = D3D10_SHADER_DEBUG,
	SkipValidation = D3D10_SHADER_SKIP_VALIDATION,
	SkipOptimization = D3D10_SHADER_SKIP_OPTIMIZATION,
	PackMatrixRowMajor = D3D10_SHADER_PACK_MATRIX_ROW_MAJOR,
	PackMatrixColumnMajor = D3D10_SHADER_PACK_MATRIX_COLUMN_MAJOR,
	PartialPrecision = D3D10_SHADER_PARTIAL_PRECISION,
	ForceSoftwareVertexShader = D3D10_SHADER_FORCE_VS_SOFTWARE_NO_OPT,
	ForceSoftwarePixelShader = D3D10_SHADER_FORCE_PS_SOFTWARE_NO_OPT,
	NoPreshader = D3D10_SHADER_NO_PRESHADER,
	AvoidFlowControl = D3D10_SHADER_AVOID_FLOW_CONTROL,
	PreferFlowControl = D3D10_SHADER_PREFER_FLOW_CONTROL,
	EnableStrictness = D3D10_SHADER_ENABLE_STRICTNESS,
	EnableBackwardsCompatibility = D3D10_SHADER_ENABLE_BACKWARDS_COMPATIBILITY,
	EnableIEEEStrictness = D3D10_SHADER_IEEE_STRICTNESS,
	WarningsAreErrors = D3D10_SHADER_WARNINGS_ARE_ERRORS,
	OptimizationLevel0 = D3D10_SHADER_OPTIMIZATION_LEVEL0,
	OptimizationLevel1 = D3D10_SHADER_OPTIMIZATION_LEVEL1,
	OptimizationLevel2 = D3D10_SHADER_OPTIMIZATION_LEVEL2,
	OptimizationLevel3 = D3D10_SHADER_OPTIMIZATION_LEVEL3
};

public enum class TextureAddressMode
{
	Wrap = D3D10_TEXTURE_ADDRESS_WRAP,
	Mirror = D3D10_TEXTURE_ADDRESS_MIRROR,
	Clamp = D3D10_TEXTURE_ADDRESS_CLAMP,
	Border = D3D10_TEXTURE_ADDRESS_BORDER,
	MirrorOnce = D3D10_TEXTURE_ADDRESS_MIRROR_ONCE
};

public enum class TextureCubeFace
{
	PositiveX = D3D10_TEXTURECUBE_FACE_POSITIVE_X,
	NegativeX = D3D10_TEXTURECUBE_FACE_NEGATIVE_X,
	PositiveY = D3D10_TEXTURECUBE_FACE_POSITIVE_Y,
	NegativeY = D3D10_TEXTURECUBE_FACE_NEGATIVE_Y,
	PositiveZ = D3D10_TEXTURECUBE_FACE_POSITIVE_Z,
	NegativeZ = D3D10_TEXTURECUBE_FACE_NEGATIVE_Z,
};

public enum class Usage
{
	Default = D3D10_USAGE_DEFAULT,
	Immutable = D3D10_USAGE_IMMUTABLE,
	Dynamic = D3D10_USAGE_DYNAMIC,
	Staging = D3D10_USAGE_STAGING
};
